### ISSUE TITLE
Split off algorithms

### ISSUE THREAD

**Issue by clue** [clue/graph#119]
Goal: Stabilizing the core graph library (plain Graph, Vertices and Edges)

The current set of algorithms is certainly what sets this library apart from other existing graph libraries. However, they're also a constant source of changes, issues and BC breaks. Also, quite a few users of this library probably won't even use a single algorithm.

As such, I'd like to split of the whole `Algorithm` namespace into a separate package. This is a short-term solution to this problem. Ideally, we should *consider* splitting this package into even more dedicated packages. This will add quite some maintenance overhead, so I'd like to postpone this until there's an actual demand.

The suggested package name would be "graphp/algorithms". Any input is welcome!

[Edit: axed] ~~Marking this ticket as "blocked", as there are quite a few PRs and issues that need review first. Splitting this off now means that we should migrate all outstanding PRs and issues over.~~

Any input is very much appreciated!

Refs #120.

**Comment by clue** [comment]
> Marking this ticket as "blocked", as there are quite a few PRs and issues that need review first. Splitting this off now means that we should migrate all outstanding PRs and issues over.

Waiting for all tickets to be resolved before splitting this off means we would end up waiting for an unknown period of time with no way to move forward.

As an alternative, we will have to make a clean cut and reject all outstanding PRs.

I wholeheartedly understand that this might be frustrating for PR authors. To mitigate this, we should work towards supporting each one to get this migrated to the final target repository.

**Comment by dav-m85** [comment]
Fair enough. Frustrated indeed, but happy the project keeps rollin :) Thanks for your watch !

**Comment by clue** [comment]
Thanks for your understanding @dav-m85! Now let's get your outstanding PRs in :)
