### ISSUE TITLE
Object storage problem

### ISSUE THREAD

**Issue by Bogdaan** [clue/graph#133]
how about realize serialize/unserialize Graph objects (i.e store in files and database)?

**Comment by clue** [comment]
Hey @Bogdaan, can you give some info on how this was resolved, just in case anybody else happens to stumble into this?

There are several options to storing graphs. Personally, I probably would have used the [graphp/graphml](https://github.com/graphp/graphml) library to write to GraphML XML-based files, which have good support in a variety of other tools.
