### ISSUE TITLE
ability to remove edge attributes

### ISSUE THREAD

**Issue by tpetry** [clue/graph#135]
At the moment you can add and update edge attributes but there's no possibility for removing an edge attribute at a later time. Neither the `Edge`-classes nor the `AttributeBag`-classes provide functionality to delete attributes.

The same is true for `Vertex` objects.

**Comment by clue** [comment]
Absolutely, this should be supported :+1: 

How do you think a possible API could look like?

This has originally been discussed as part of #103, so some of the original discussion can be found in there. Afaict the main issue was telling non-existant and `null` values apart.

**Comment by tpetry** [comment]
What's wrong with a simple `removeAttribute($name)` method? Simple, clean and self-explanatory - no need to make complicated.

**Comment by dav-m85** [comment]
Agreed :+1:

**Comment by clue** [comment]
I agree :+1: Does anybody feel like filing a PR? :-)
