### ISSUE TITLE
How to populate verticesStorage

### ISSUE THREAD

**Issue by melokki** [clue/graph#155]
Hello,
I want to use this lib intro a project of mine, but it's a bit unclear to me how to use it exactly.
For instance, I see in the Graph class that there is a `addVertex` method, but the comment tells `adds a new Vertex to the Graph (MUST NOT be called manually!)`

I don't understand, where is this method used if is meant to not be called manually.

This method does what I want, populates the `verticesStorage` array with a new Vertex object, but the `createVertex` method just return a vertex object. 

So my question is, how do I populate the `verticesStorage` without `addVertex` method? Or what is the purpose of the `verticesStorage`?
I want later to apply the Dijkstra algorithm on this graph.

**Comment by melokki** [comment]
Now when I create a new vertex using the `createVertex` method when I call the `getVertices` method on the graph object I can see my newly created vertex. 
It's strange, last night I could not see it.

**Comment by clue** [comment]
Hi @melokki, I agree that the documentation could certainly use an update here :-) Happy to see you've found the `createVertex()` method which should do what you're looking for.

I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can reopen this :+1:

**Comment by melokki** [comment]
Yes, my question has been answered.
I've looked more deep into the code and I saw how the `addVertex` method is used and from where.

I'll try maybe to put something together and come back with an update for the documentation, but first I need to understand correctly how I can use the library :)
