### ISSUE TITLE
Is there a way to check DAG with this library?

### ISSUE THREAD

**Issue by seyfer** [clue/graph#159]
https://en.wikipedia.org/wiki/Directed_acyclic_graph

I have expected to see method like `$graph->isAcyclic()`.

**Comment by clue** [comment]
I very much welcome PRs to implement https://github.com/graphp/algorithms/issues/2 :shipit: 

In the meantime, you may use `TopologicalSort` for check for cycles: https://github.com/graphp/algorithms/blob/master/src/TopologicalSort.php

I hope this helps :+1:
