### ISSUE TITLE
Johnson's algorithm for finding cycles

### ISSUE THREAD

**Issue by flip111** [clue/graph#160]
Would be nice if there was an implementation of Johnson's algorithm. I have a graph with a few cycles i like to disconnect one by one, for that i like to get a list of all the cycles sorted by the length (amount of nodes) in the cycle.

Reference:

https://stackoverflow.com/questions/546655/finding-all-cycles-in-a-directed-graph

Python implementation: https://networkx.github.io/documentation/networkx-1.10/_modules/networkx/algorithms/cycles.html#simple_cycles

**Comment by clue** [comment]
PRs to implement this would be much appreciated, see https://github.com/graphp/algorithms/issues/2 :shipit: :+1:
