### ISSUE TITLE
Edge has no __toString()

### ISSUE THREAD

**Issue by clemens-tolboom** [clue/graph#23]
Trying to 
```php
echo $edge;
```
a single edge is not an option right now.

Should we add this?

**Comment by clue** [comment]
> Simply put, I'm not quite happy with this concept, so perhaps we should reconsider if adding a `__toString()` is actually a good idea. See also [__toString() or not __toString()?](http://pooteeweet.org/blog/2231).

I still think it's a bad idea to implement `__toString()` on either the `Graph`, `Vertex` or `Edge`.

We're working towards splitting off individual components via #120.
As such, GraphViz and GraphML have been moved to individual components already.
The TrivialGraphExporter is the only remaining exporter in this repo and will eventually be split off via #121.
There's little purpose in keeping the then useless `Exporter` namespace. It will be removed via #122.

As such, I don't think this repo should provide a default exporter for either of our entities.

That being said, I still consider external `Exporter`s a valid and useful feature. They provide a SOLID design and work out well.
